version: '3.9'
services:
  db :
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure
        
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 256M
      restart_policy:
        condition: on-failure

  