version: '3.9'
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    networks:
      - app-network
        
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.3"
  #         memory: 256M
  #       reservations:
  #         cpus: "0.1"
  #         memory: 256M
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - app-network

  # backend:
  #   build:
  #     dockerfile: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/backend/:app
  #   depends_on:
  #     - db
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M
  #       reservations:
  #         cpus: '0.2'
  #         memory: 256M
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge